// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/v1/varlet.proto

package varletv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetentionPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinVersions   int32                  `protobuf:"varint,1,opt,name=min_versions,json=minVersions,proto3" json:"min_versions,omitempty"`
	MaxAgeDays    int32                  `protobuf:"varint,2,opt,name=max_age_days,json=maxAgeDays,proto3" json:"max_age_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	mi := &file_proto_v1_varlet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{0}
}

func (x *RetentionPolicy) GetMinVersions() int32 {
	if x != nil {
		return x.MinVersions
	}
	return 0
}

func (x *RetentionPolicy) GetMaxAgeDays() int32 {
	if x != nil {
		return x.MaxAgeDays
	}
	return 0
}

type RegisterNamespaceRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RetentionPolicy     *RetentionPolicy       `protobuf:"bytes,2,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	RunWebhookUrl       string                 `protobuf:"bytes,3,opt,name=run_webhook_url,json=runWebhookUrl,proto3" json:"run_webhook_url,omitempty"`
	WebhookDelayMinutes int32                  `protobuf:"varint,4,opt,name=webhook_delay_minutes,json=webhookDelayMinutes,proto3" json:"webhook_delay_minutes,omitempty"`
	DedupDelayMinutes   int32                  `protobuf:"varint,5,opt,name=dedup_delay_minutes,json=dedupDelayMinutes,proto3" json:"dedup_delay_minutes,omitempty"`
	MaxDedupChanges     int32                  `protobuf:"varint,6,opt,name=max_dedup_changes,json=maxDedupChanges,proto3" json:"max_dedup_changes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterNamespaceRequest) Reset() {
	*x = RegisterNamespaceRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNamespaceRequest) ProtoMessage() {}

func (x *RegisterNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNamespaceRequest.ProtoReflect.Descriptor instead.
func (*RegisterNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterNamespaceRequest) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *RegisterNamespaceRequest) GetRunWebhookUrl() string {
	if x != nil {
		return x.RunWebhookUrl
	}
	return ""
}

func (x *RegisterNamespaceRequest) GetWebhookDelayMinutes() int32 {
	if x != nil {
		return x.WebhookDelayMinutes
	}
	return 0
}

func (x *RegisterNamespaceRequest) GetDedupDelayMinutes() int32 {
	if x != nil {
		return x.DedupDelayMinutes
	}
	return 0
}

func (x *RegisterNamespaceRequest) GetMaxDedupChanges() int32 {
	if x != nil {
		return x.MaxDedupChanges
	}
	return 0
}

type RegisterNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNamespaceResponse) Reset() {
	*x = RegisterNamespaceResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNamespaceResponse) ProtoMessage() {}

func (x *RegisterNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNamespaceResponse.ProtoReflect.Descriptor instead.
func (*RegisterNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNamespaceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{3}
}

func (x *GetNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNamespaceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllowedConsumers    []string               `protobuf:"bytes,2,rep,name=allowed_consumers,json=allowedConsumers,proto3" json:"allowed_consumers,omitempty"` // Allowlist of consumer namespaces (supports wildcards)
	RetentionPolicy     *RetentionPolicy       `protobuf:"bytes,3,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	RunWebhookUrl       string                 `protobuf:"bytes,4,opt,name=run_webhook_url,json=runWebhookUrl,proto3" json:"run_webhook_url,omitempty"`
	WebhookDelayMinutes int32                  `protobuf:"varint,5,opt,name=webhook_delay_minutes,json=webhookDelayMinutes,proto3" json:"webhook_delay_minutes,omitempty"`
	DedupDelayMinutes   int32                  `protobuf:"varint,6,opt,name=dedup_delay_minutes,json=dedupDelayMinutes,proto3" json:"dedup_delay_minutes,omitempty"`
	MaxDedupChanges     int32                  `protobuf:"varint,7,opt,name=max_dedup_changes,json=maxDedupChanges,proto3" json:"max_dedup_changes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetNamespaceResponse) Reset() {
	*x = GetNamespaceResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceResponse) ProtoMessage() {}

func (x *GetNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{4}
}

func (x *GetNamespaceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNamespaceResponse) GetAllowedConsumers() []string {
	if x != nil {
		return x.AllowedConsumers
	}
	return nil
}

func (x *GetNamespaceResponse) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *GetNamespaceResponse) GetRunWebhookUrl() string {
	if x != nil {
		return x.RunWebhookUrl
	}
	return ""
}

func (x *GetNamespaceResponse) GetWebhookDelayMinutes() int32 {
	if x != nil {
		return x.WebhookDelayMinutes
	}
	return 0
}

func (x *GetNamespaceResponse) GetDedupDelayMinutes() int32 {
	if x != nil {
		return x.DedupDelayMinutes
	}
	return 0
}

func (x *GetNamespaceResponse) GetMaxDedupChanges() int32 {
	if x != nil {
		return x.MaxDedupChanges
	}
	return 0
}

type PutVariableRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value          *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ForceActuation bool                   `protobuf:"varint,4,opt,name=force_actuation,json=forceActuation,proto3" json:"force_actuation,omitempty"` // If true, force consumers to re-apply even if value is unchanged
	ActuationUuid  string                 `protobuf:"bytes,5,opt,name=actuation_uuid,json=actuationUuid,proto3" json:"actuation_uuid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutVariableRequest) Reset() {
	*x = PutVariableRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVariableRequest) ProtoMessage() {}

func (x *PutVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVariableRequest.ProtoReflect.Descriptor instead.
func (*PutVariableRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{5}
}

func (x *PutVariableRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutVariableRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutVariableRequest) GetForceActuation() bool {
	if x != nil {
		return x.ForceActuation
	}
	return false
}

func (x *PutVariableRequest) GetActuationUuid() string {
	if x != nil {
		return x.ActuationUuid
	}
	return ""
}

type PutVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutVariableResponse) Reset() {
	*x = PutVariableResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVariableResponse) ProtoMessage() {}

func (x *PutVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVariableResponse.ProtoReflect.Descriptor instead.
func (*PutVariableResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{6}
}

type DeleteVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"` // If true, force deletion even if there are active consumers.
	ActuationUuid string                 `protobuf:"bytes,4,opt,name=actuation_uuid,json=actuationUuid,proto3" json:"actuation_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableRequest) Reset() {
	*x = DeleteVariableRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableRequest) ProtoMessage() {}

func (x *DeleteVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableRequest.ProtoReflect.Descriptor instead.
func (*DeleteVariableRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVariableRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteVariableRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DeleteVariableRequest) GetActuationUuid() string {
	if x != nil {
		return x.ActuationUuid
	}
	return ""
}

type DeleteVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableResponse) Reset() {
	*x = DeleteVariableResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableResponse) ProtoMessage() {}

func (x *DeleteVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableResponse.ProtoReflect.Descriptor instead.
func (*DeleteVariableResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{8}
}

type RegisterConsumerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterConsumerRequest) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *RegisterConsumerRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *RegisterConsumerRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type RegisterConsumerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                                          // Returns the current value upon registration
	ActuationNonce int64                  `protobuf:"varint,2,opt,name=actuation_nonce,json=actuationNonce,proto3" json:"actuation_nonce,omitempty"` // Token to trigger downstream recreation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterConsumerResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RegisterConsumerResponse) GetActuationNonce() int64 {
	if x != nil {
		return x.ActuationNonce
	}
	return 0
}

type DeregisterConsumerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeregisterConsumerRequest) Reset() {
	*x = DeregisterConsumerRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterConsumerRequest) ProtoMessage() {}

func (x *DeregisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{11}
}

func (x *DeregisterConsumerRequest) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *DeregisterConsumerRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *DeregisterConsumerRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type DeregisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterConsumerResponse) Reset() {
	*x = DeregisterConsumerResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterConsumerResponse) ProtoMessage() {}

func (x *DeregisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{12}
}

type GetVariableValueRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetVariableValueRequest) Reset() {
	*x = GetVariableValueRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableValueRequest) ProtoMessage() {}

func (x *GetVariableValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableValueRequest.ProtoReflect.Descriptor instead.
func (*GetVariableValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{13}
}

func (x *GetVariableValueRequest) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *GetVariableValueRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *GetVariableValueRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type GetVariableValueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ActuationNonce int64                  `protobuf:"varint,2,opt,name=actuation_nonce,json=actuationNonce,proto3" json:"actuation_nonce,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVariableValueResponse) Reset() {
	*x = GetVariableValueResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableValueResponse) ProtoMessage() {}

func (x *GetVariableValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableValueResponse.ProtoReflect.Descriptor instead.
func (*GetVariableValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{14}
}

func (x *GetVariableValueResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetVariableValueResponse) GetActuationNonce() int64 {
	if x != nil {
		return x.ActuationNonce
	}
	return 0
}

type SetNamespacePolicyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AllowedConsumers []string               `protobuf:"bytes,2,rep,name=allowed_consumers,json=allowedConsumers,proto3" json:"allowed_consumers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetNamespacePolicyRequest) Reset() {
	*x = SetNamespacePolicyRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespacePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespacePolicyRequest) ProtoMessage() {}

func (x *SetNamespacePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespacePolicyRequest.ProtoReflect.Descriptor instead.
func (*SetNamespacePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{15}
}

func (x *SetNamespacePolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetNamespacePolicyRequest) GetAllowedConsumers() []string {
	if x != nil {
		return x.AllowedConsumers
	}
	return nil
}

type SetNamespacePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNamespacePolicyResponse) Reset() {
	*x = SetNamespacePolicyResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespacePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespacePolicyResponse) ProtoMessage() {}

func (x *SetNamespacePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespacePolicyResponse.ProtoReflect.Descriptor instead.
func (*SetNamespacePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{16}
}

type GetDependencyGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                               // Optional root namespace
	UpstreamDepth int32                  `protobuf:"varint,2,opt,name=upstream_depth,json=upstreamDepth,proto3" json:"upstream_depth,omitempty"` // Number of parent levels to include (default = 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependencyGraphRequest) Reset() {
	*x = GetDependencyGraphRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependencyGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyGraphRequest) ProtoMessage() {}

func (x *GetDependencyGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyGraphRequest.ProtoReflect.Descriptor instead.
func (*GetDependencyGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{17}
}

func (x *GetDependencyGraphRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetDependencyGraphRequest) GetUpstreamDepth() int32 {
	if x != nil {
		return x.UpstreamDepth
	}
	return 0
}

type DependencyEdge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DependencyEdge) Reset() {
	*x = DependencyEdge{}
	mi := &file_proto_v1_varlet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyEdge) ProtoMessage() {}

func (x *DependencyEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyEdge.ProtoReflect.Descriptor instead.
func (*DependencyEdge) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{18}
}

func (x *DependencyEdge) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *DependencyEdge) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *DependencyEdge) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type GetDependencyGraphResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Namespaces    []string                        `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Edges         []*DependencyEdge               `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Statuses      map[string]*NamespaceStatusInfo `protobuf:"bytes,3,rep,name=statuses,proto3" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependencyGraphResponse) Reset() {
	*x = GetDependencyGraphResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependencyGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyGraphResponse) ProtoMessage() {}

func (x *GetDependencyGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyGraphResponse.ProtoReflect.Descriptor instead.
func (*GetDependencyGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{19}
}

func (x *GetDependencyGraphResponse) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *GetDependencyGraphResponse) GetEdges() []*DependencyEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *GetDependencyGraphResponse) GetStatuses() map[string]*NamespaceStatusInfo {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type NamespaceStatusInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Status                   string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CausalActuationUuids     []string               `protobuf:"bytes,2,rep,name=causal_actuation_uuids,json=causalActuationUuids,proto3" json:"causal_actuation_uuids,omitempty"`
	ActiveActuationUuid      string                 `protobuf:"bytes,3,opt,name=active_actuation_uuid,json=activeActuationUuid,proto3" json:"active_actuation_uuid,omitempty"`
	LastActuationUuid        string                 `protobuf:"bytes,4,opt,name=last_actuation_uuid,json=lastActuationUuid,proto3" json:"last_actuation_uuid,omitempty"`
	ActiveActuationStartTime int64                  `protobuf:"varint,5,opt,name=active_actuation_start_time,json=activeActuationStartTime,proto3" json:"active_actuation_start_time,omitempty"`
	LastActuationTime        int64                  `protobuf:"varint,6,opt,name=last_actuation_time,json=lastActuationTime,proto3" json:"last_actuation_time,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NamespaceStatusInfo) Reset() {
	*x = NamespaceStatusInfo{}
	mi := &file_proto_v1_varlet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceStatusInfo) ProtoMessage() {}

func (x *NamespaceStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceStatusInfo.ProtoReflect.Descriptor instead.
func (*NamespaceStatusInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{20}
}

func (x *NamespaceStatusInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NamespaceStatusInfo) GetCausalActuationUuids() []string {
	if x != nil {
		return x.CausalActuationUuids
	}
	return nil
}

func (x *NamespaceStatusInfo) GetActiveActuationUuid() string {
	if x != nil {
		return x.ActiveActuationUuid
	}
	return ""
}

func (x *NamespaceStatusInfo) GetLastActuationUuid() string {
	if x != nil {
		return x.LastActuationUuid
	}
	return ""
}

func (x *NamespaceStatusInfo) GetActiveActuationStartTime() int64 {
	if x != nil {
		return x.ActiveActuationStartTime
	}
	return 0
}

func (x *NamespaceStatusInfo) GetLastActuationTime() int64 {
	if x != nil {
		return x.LastActuationTime
	}
	return 0
}

type TraceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix epoch seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceNode) Reset() {
	*x = TraceNode{}
	mi := &file_proto_v1_varlet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceNode) ProtoMessage() {}

func (x *TraceNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceNode.ProtoReflect.Descriptor instead.
func (*TraceNode) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{21}
}

func (x *TraceNode) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TraceNode) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TraceNode) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TraceNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TraceNode) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TraceEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildUuid     string                 `protobuf:"bytes,1,opt,name=child_uuid,json=childUuid,proto3" json:"child_uuid,omitempty"`
	ParentUuid    string                 `protobuf:"bytes,2,opt,name=parent_uuid,json=parentUuid,proto3" json:"parent_uuid,omitempty"`
	VariableNames []string               `protobuf:"bytes,3,rep,name=variable_names,json=variableNames,proto3" json:"variable_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEdge) Reset() {
	*x = TraceEdge{}
	mi := &file_proto_v1_varlet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEdge) ProtoMessage() {}

func (x *TraceEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEdge.ProtoReflect.Descriptor instead.
func (*TraceEdge) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{22}
}

func (x *TraceEdge) GetChildUuid() string {
	if x != nil {
		return x.ChildUuid
	}
	return ""
}

func (x *TraceEdge) GetParentUuid() string {
	if x != nil {
		return x.ParentUuid
	}
	return ""
}

func (x *TraceEdge) GetVariableNames() []string {
	if x != nil {
		return x.VariableNames
	}
	return nil
}

type GetActuationTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActuationUuid string                 `protobuf:"bytes,1,opt,name=actuation_uuid,json=actuationUuid,proto3" json:"actuation_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActuationTraceRequest) Reset() {
	*x = GetActuationTraceRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActuationTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActuationTraceRequest) ProtoMessage() {}

func (x *GetActuationTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActuationTraceRequest.ProtoReflect.Descriptor instead.
func (*GetActuationTraceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{23}
}

func (x *GetActuationTraceRequest) GetActuationUuid() string {
	if x != nil {
		return x.ActuationUuid
	}
	return ""
}

type GetActuationTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TraceNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*TraceEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActuationTraceResponse) Reset() {
	*x = GetActuationTraceResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActuationTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActuationTraceResponse) ProtoMessage() {}

func (x *GetActuationTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActuationTraceResponse.ProtoReflect.Descriptor instead.
func (*GetActuationTraceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{24}
}

func (x *GetActuationTraceResponse) GetNodes() []*TraceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetActuationTraceResponse) GetEdges() []*TraceEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type StartActuationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Namespace            string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ActuationUuid        string                 `protobuf:"bytes,2,opt,name=actuation_uuid,json=actuationUuid,proto3" json:"actuation_uuid,omitempty"`
	ParentActuationUuids []string               `protobuf:"bytes,3,rep,name=parent_actuation_uuids,json=parentActuationUuids,proto3" json:"parent_actuation_uuids,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartActuationRequest) Reset() {
	*x = StartActuationRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartActuationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartActuationRequest) ProtoMessage() {}

func (x *StartActuationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartActuationRequest.ProtoReflect.Descriptor instead.
func (*StartActuationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{25}
}

func (x *StartActuationRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StartActuationRequest) GetActuationUuid() string {
	if x != nil {
		return x.ActuationUuid
	}
	return ""
}

func (x *StartActuationRequest) GetParentActuationUuids() []string {
	if x != nil {
		return x.ParentActuationUuids
	}
	return nil
}

type StartActuationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartActuationResponse) Reset() {
	*x = StartActuationResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartActuationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartActuationResponse) ProtoMessage() {}

func (x *StartActuationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartActuationResponse.ProtoReflect.Descriptor instead.
func (*StartActuationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{26}
}

type RegisterCompletionHookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCompletionHookRequest) Reset() {
	*x = RegisterCompletionHookRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCompletionHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCompletionHookRequest) ProtoMessage() {}

func (x *RegisterCompletionHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCompletionHookRequest.ProtoReflect.Descriptor instead.
func (*RegisterCompletionHookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{27}
}

func (x *RegisterCompletionHookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RegisterCompletionHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCompletionHookResponse) Reset() {
	*x = RegisterCompletionHookResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCompletionHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCompletionHookResponse) ProtoMessage() {}

func (x *RegisterCompletionHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCompletionHookResponse.ProtoReflect.Descriptor instead.
func (*RegisterCompletionHookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{28}
}

type DeregisterCompletionHookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterCompletionHookRequest) Reset() {
	*x = DeregisterCompletionHookRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterCompletionHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterCompletionHookRequest) ProtoMessage() {}

func (x *DeregisterCompletionHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterCompletionHookRequest.ProtoReflect.Descriptor instead.
func (*DeregisterCompletionHookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{29}
}

func (x *DeregisterCompletionHookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeregisterCompletionHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterCompletionHookResponse) Reset() {
	*x = DeregisterCompletionHookResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterCompletionHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterCompletionHookResponse) ProtoMessage() {}

func (x *DeregisterCompletionHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterCompletionHookResponse.ProtoReflect.Descriptor instead.
func (*DeregisterCompletionHookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{30}
}

type ListCompletionHooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompletionHooksRequest) Reset() {
	*x = ListCompletionHooksRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompletionHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompletionHooksRequest) ProtoMessage() {}

func (x *ListCompletionHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompletionHooksRequest.ProtoReflect.Descriptor instead.
func (*ListCompletionHooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{31}
}

type ListCompletionHooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCompletionHooksResponse) Reset() {
	*x = ListCompletionHooksResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCompletionHooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCompletionHooksResponse) ProtoMessage() {}

func (x *ListCompletionHooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCompletionHooksResponse.ProtoReflect.Descriptor instead.
func (*ListCompletionHooksResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{32}
}

func (x *ListCompletionHooksResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_proto_v1_varlet_proto protoreflect.FileDescriptor

const file_proto_v1_varlet_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/varlet.proto\x12\tvarlet.v1\x1a\x1cgoogle/protobuf/struct.proto\"V\n" +
	"\x0fRetentionPolicy\x12!\n" +
	"\fmin_versions\x18\x01 \x01(\x05R\vminVersions\x12 \n" +
	"\fmax_age_days\x18\x02 \x01(\x05R\n" +
	"maxAgeDays\"\xad\x02\n" +
	"\x18RegisterNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12E\n" +
	"\x10retention_policy\x18\x02 \x01(\v2\x1a.varlet.v1.RetentionPolicyR\x0fretentionPolicy\x12&\n" +
	"\x0frun_webhook_url\x18\x03 \x01(\tR\rrunWebhookUrl\x122\n" +
	"\x15webhook_delay_minutes\x18\x04 \x01(\x05R\x13webhookDelayMinutes\x12.\n" +
	"\x13dedup_delay_minutes\x18\x05 \x01(\x05R\x11dedupDelayMinutes\x12*\n" +
	"\x11max_dedup_changes\x18\x06 \x01(\x05R\x0fmaxDedupChanges\"/\n" +
	"\x19RegisterNamespaceResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13GetNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd6\x02\n" +
	"\x14GetNamespaceResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x11allowed_consumers\x18\x02 \x03(\tR\x10allowedConsumers\x12E\n" +
	"\x10retention_policy\x18\x03 \x01(\v2\x1a.varlet.v1.RetentionPolicyR\x0fretentionPolicy\x12&\n" +
	"\x0frun_webhook_url\x18\x04 \x01(\tR\rrunWebhookUrl\x122\n" +
	"\x15webhook_delay_minutes\x18\x05 \x01(\x05R\x13webhookDelayMinutes\x12.\n" +
	"\x13dedup_delay_minutes\x18\x06 \x01(\x05R\x11dedupDelayMinutes\x12*\n" +
	"\x11max_dedup_changes\x18\a \x01(\x05R\x0fmaxDedupChanges\"\xc4\x01\n" +
	"\x12PutVariableRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12'\n" +
	"\x0fforce_actuation\x18\x04 \x01(\bR\x0eforceActuation\x12%\n" +
	"\x0eactuation_uuid\x18\x05 \x01(\tR\ractuationUuid\"\x15\n" +
	"\x13PutVariableResponse\"\x86\x01\n" +
	"\x15DeleteVariableRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12%\n" +
	"\x0eactuation_uuid\x18\x04 \x01(\tR\ractuationUuid\"\x18\n" +
	"\x16DeleteVariableResponse\"\x98\x01\n" +
	"\x17RegisterConsumerRequest\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"q\n" +
	"\x18RegisterConsumerResponse\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12'\n" +
	"\x0factuation_nonce\x18\x02 \x01(\x03R\x0eactuationNonce\"\x9a\x01\n" +
	"\x19DeregisterConsumerRequest\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"\x1c\n" +
	"\x1aDeregisterConsumerResponse\"\x98\x01\n" +
	"\x17GetVariableValueRequest\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"q\n" +
	"\x18GetVariableValueResponse\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12'\n" +
	"\x0factuation_nonce\x18\x02 \x01(\x03R\x0eactuationNonce\"f\n" +
	"\x19SetNamespacePolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12+\n" +
	"\x11allowed_consumers\x18\x02 \x03(\tR\x10allowedConsumers\"\x1c\n" +
	"\x1aSetNamespacePolicyResponse\"`\n" +
	"\x19GetDependencyGraphRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12%\n" +
	"\x0eupstream_depth\x18\x02 \x01(\x05R\rupstreamDepth\"\x8f\x01\n" +
	"\x0eDependencyEdge\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"\x9b\x02\n" +
	"\x1aGetDependencyGraphResponse\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12/\n" +
	"\x05edges\x18\x02 \x03(\v2\x19.varlet.v1.DependencyEdgeR\x05edges\x12O\n" +
	"\bstatuses\x18\x03 \x03(\v23.varlet.v1.GetDependencyGraphResponse.StatusesEntryR\bstatuses\x1a[\n" +
	"\rStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.varlet.v1.NamespaceStatusInfoR\x05value:\x028\x01\"\xb6\x02\n" +
	"\x13NamespaceStatusInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x124\n" +
	"\x16causal_actuation_uuids\x18\x02 \x03(\tR\x14causalActuationUuids\x122\n" +
	"\x15active_actuation_uuid\x18\x03 \x01(\tR\x13activeActuationUuid\x12.\n" +
	"\x13last_actuation_uuid\x18\x04 \x01(\tR\x11lastActuationUuid\x12=\n" +
	"\x1bactive_actuation_start_time\x18\x05 \x01(\x03R\x18activeActuationStartTime\x12.\n" +
	"\x13last_actuation_time\x18\x06 \x01(\x03R\x11lastActuationTime\"\x8b\x01\n" +
	"\tTraceNode\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"r\n" +
	"\tTraceEdge\x12\x1d\n" +
	"\n" +
	"child_uuid\x18\x01 \x01(\tR\tchildUuid\x12\x1f\n" +
	"\vparent_uuid\x18\x02 \x01(\tR\n" +
	"parentUuid\x12%\n" +
	"\x0evariable_names\x18\x03 \x03(\tR\rvariableNames\"A\n" +
	"\x18GetActuationTraceRequest\x12%\n" +
	"\x0eactuation_uuid\x18\x01 \x01(\tR\ractuationUuid\"s\n" +
	"\x19GetActuationTraceResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.varlet.v1.TraceNodeR\x05nodes\x12*\n" +
	"\x05edges\x18\x02 \x03(\v2\x14.varlet.v1.TraceEdgeR\x05edges\"\x92\x01\n" +
	"\x15StartActuationRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12%\n" +
	"\x0eactuation_uuid\x18\x02 \x01(\tR\ractuationUuid\x124\n" +
	"\x16parent_actuation_uuids\x18\x03 \x03(\tR\x14parentActuationUuids\"\x18\n" +
	"\x16StartActuationResponse\"1\n" +
	"\x1dRegisterCompletionHookRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\" \n" +
	"\x1eRegisterCompletionHookResponse\"3\n" +
	"\x1fDeregisterCompletionHookRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\"\n" +
	" DeregisterCompletionHookResponse\"\x1c\n" +
	"\x1aListCompletionHooksRequest\"1\n" +
	"\x1bListCompletionHooksResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls2\xc9\n" +
	"\n" +
	"\rVarletService\x12^\n" +
	"\x11RegisterNamespace\x12#.varlet.v1.RegisterNamespaceRequest\x1a$.varlet.v1.RegisterNamespaceResponse\x12O\n" +
	"\fGetNamespace\x12\x1e.varlet.v1.GetNamespaceRequest\x1a\x1f.varlet.v1.GetNamespaceResponse\x12a\n" +
	"\x12SetNamespacePolicy\x12$.varlet.v1.SetNamespacePolicyRequest\x1a%.varlet.v1.SetNamespacePolicyResponse\x12L\n" +
	"\vPutVariable\x12\x1d.varlet.v1.PutVariableRequest\x1a\x1e.varlet.v1.PutVariableResponse\x12U\n" +
	"\x0eDeleteVariable\x12 .varlet.v1.DeleteVariableRequest\x1a!.varlet.v1.DeleteVariableResponse\x12[\n" +
	"\x10RegisterConsumer\x12\".varlet.v1.RegisterConsumerRequest\x1a#.varlet.v1.RegisterConsumerResponse\x12a\n" +
	"\x12DeregisterConsumer\x12$.varlet.v1.DeregisterConsumerRequest\x1a%.varlet.v1.DeregisterConsumerResponse\x12[\n" +
	"\x10GetVariableValue\x12\".varlet.v1.GetVariableValueRequest\x1a#.varlet.v1.GetVariableValueResponse\x12U\n" +
	"\x0eStartActuation\x12 .varlet.v1.StartActuationRequest\x1a!.varlet.v1.StartActuationResponse\x12a\n" +
	"\x12GetDependencyGraph\x12$.varlet.v1.GetDependencyGraphRequest\x1a%.varlet.v1.GetDependencyGraphResponse\x12^\n" +
	"\x11GetActuationTrace\x12#.varlet.v1.GetActuationTraceRequest\x1a$.varlet.v1.GetActuationTraceResponse\x12m\n" +
	"\x16RegisterCompletionHook\x12(.varlet.v1.RegisterCompletionHookRequest\x1a).varlet.v1.RegisterCompletionHookResponse\x12s\n" +
	"\x18DeregisterCompletionHook\x12*.varlet.v1.DeregisterCompletionHookRequest\x1a+.varlet.v1.DeregisterCompletionHookResponse\x12d\n" +
	"\x13ListCompletionHooks\x12%.varlet.v1.ListCompletionHooksRequest\x1a&.varlet.v1.ListCompletionHooksResponseB,Z*github.com/google/varlet/proto/v1;varletv1b\x06proto3"

var (
	file_proto_v1_varlet_proto_rawDescOnce sync.Once
	file_proto_v1_varlet_proto_rawDescData []byte
)

func file_proto_v1_varlet_proto_rawDescGZIP() []byte {
	file_proto_v1_varlet_proto_rawDescOnce.Do(func() {
		file_proto_v1_varlet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_varlet_proto_rawDesc), len(file_proto_v1_varlet_proto_rawDesc)))
	})
	return file_proto_v1_varlet_proto_rawDescData
}

var file_proto_v1_varlet_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_v1_varlet_proto_goTypes = []any{
	(*RetentionPolicy)(nil),                  // 0: varlet.v1.RetentionPolicy
	(*RegisterNamespaceRequest)(nil),         // 1: varlet.v1.RegisterNamespaceRequest
	(*RegisterNamespaceResponse)(nil),        // 2: varlet.v1.RegisterNamespaceResponse
	(*GetNamespaceRequest)(nil),              // 3: varlet.v1.GetNamespaceRequest
	(*GetNamespaceResponse)(nil),             // 4: varlet.v1.GetNamespaceResponse
	(*PutVariableRequest)(nil),               // 5: varlet.v1.PutVariableRequest
	(*PutVariableResponse)(nil),              // 6: varlet.v1.PutVariableResponse
	(*DeleteVariableRequest)(nil),            // 7: varlet.v1.DeleteVariableRequest
	(*DeleteVariableResponse)(nil),           // 8: varlet.v1.DeleteVariableResponse
	(*RegisterConsumerRequest)(nil),          // 9: varlet.v1.RegisterConsumerRequest
	(*RegisterConsumerResponse)(nil),         // 10: varlet.v1.RegisterConsumerResponse
	(*DeregisterConsumerRequest)(nil),        // 11: varlet.v1.DeregisterConsumerRequest
	(*DeregisterConsumerResponse)(nil),       // 12: varlet.v1.DeregisterConsumerResponse
	(*GetVariableValueRequest)(nil),          // 13: varlet.v1.GetVariableValueRequest
	(*GetVariableValueResponse)(nil),         // 14: varlet.v1.GetVariableValueResponse
	(*SetNamespacePolicyRequest)(nil),        // 15: varlet.v1.SetNamespacePolicyRequest
	(*SetNamespacePolicyResponse)(nil),       // 16: varlet.v1.SetNamespacePolicyResponse
	(*GetDependencyGraphRequest)(nil),        // 17: varlet.v1.GetDependencyGraphRequest
	(*DependencyEdge)(nil),                   // 18: varlet.v1.DependencyEdge
	(*GetDependencyGraphResponse)(nil),       // 19: varlet.v1.GetDependencyGraphResponse
	(*NamespaceStatusInfo)(nil),              // 20: varlet.v1.NamespaceStatusInfo
	(*TraceNode)(nil),                        // 21: varlet.v1.TraceNode
	(*TraceEdge)(nil),                        // 22: varlet.v1.TraceEdge
	(*GetActuationTraceRequest)(nil),         // 23: varlet.v1.GetActuationTraceRequest
	(*GetActuationTraceResponse)(nil),        // 24: varlet.v1.GetActuationTraceResponse
	(*StartActuationRequest)(nil),            // 25: varlet.v1.StartActuationRequest
	(*StartActuationResponse)(nil),           // 26: varlet.v1.StartActuationResponse
	(*RegisterCompletionHookRequest)(nil),    // 27: varlet.v1.RegisterCompletionHookRequest
	(*RegisterCompletionHookResponse)(nil),   // 28: varlet.v1.RegisterCompletionHookResponse
	(*DeregisterCompletionHookRequest)(nil),  // 29: varlet.v1.DeregisterCompletionHookRequest
	(*DeregisterCompletionHookResponse)(nil), // 30: varlet.v1.DeregisterCompletionHookResponse
	(*ListCompletionHooksRequest)(nil),       // 31: varlet.v1.ListCompletionHooksRequest
	(*ListCompletionHooksResponse)(nil),      // 32: varlet.v1.ListCompletionHooksResponse
	nil,                                      // 33: varlet.v1.GetDependencyGraphResponse.StatusesEntry
	(*structpb.Value)(nil),                   // 34: google.protobuf.Value
}
var file_proto_v1_varlet_proto_depIdxs = []int32{
	0,  // 0: varlet.v1.RegisterNamespaceRequest.retention_policy:type_name -> varlet.v1.RetentionPolicy
	0,  // 1: varlet.v1.GetNamespaceResponse.retention_policy:type_name -> varlet.v1.RetentionPolicy
	34, // 2: varlet.v1.PutVariableRequest.value:type_name -> google.protobuf.Value
	34, // 3: varlet.v1.RegisterConsumerResponse.value:type_name -> google.protobuf.Value
	34, // 4: varlet.v1.GetVariableValueResponse.value:type_name -> google.protobuf.Value
	18, // 5: varlet.v1.GetDependencyGraphResponse.edges:type_name -> varlet.v1.DependencyEdge
	33, // 6: varlet.v1.GetDependencyGraphResponse.statuses:type_name -> varlet.v1.GetDependencyGraphResponse.StatusesEntry
	21, // 7: varlet.v1.GetActuationTraceResponse.nodes:type_name -> varlet.v1.TraceNode
	22, // 8: varlet.v1.GetActuationTraceResponse.edges:type_name -> varlet.v1.TraceEdge
	20, // 9: varlet.v1.GetDependencyGraphResponse.StatusesEntry.value:type_name -> varlet.v1.NamespaceStatusInfo
	1,  // 10: varlet.v1.VarletService.RegisterNamespace:input_type -> varlet.v1.RegisterNamespaceRequest
	3,  // 11: varlet.v1.VarletService.GetNamespace:input_type -> varlet.v1.GetNamespaceRequest
	15, // 12: varlet.v1.VarletService.SetNamespacePolicy:input_type -> varlet.v1.SetNamespacePolicyRequest
	5,  // 13: varlet.v1.VarletService.PutVariable:input_type -> varlet.v1.PutVariableRequest
	7,  // 14: varlet.v1.VarletService.DeleteVariable:input_type -> varlet.v1.DeleteVariableRequest
	9,  // 15: varlet.v1.VarletService.RegisterConsumer:input_type -> varlet.v1.RegisterConsumerRequest
	11, // 16: varlet.v1.VarletService.DeregisterConsumer:input_type -> varlet.v1.DeregisterConsumerRequest
	13, // 17: varlet.v1.VarletService.GetVariableValue:input_type -> varlet.v1.GetVariableValueRequest
	25, // 18: varlet.v1.VarletService.StartActuation:input_type -> varlet.v1.StartActuationRequest
	17, // 19: varlet.v1.VarletService.GetDependencyGraph:input_type -> varlet.v1.GetDependencyGraphRequest
	23, // 20: varlet.v1.VarletService.GetActuationTrace:input_type -> varlet.v1.GetActuationTraceRequest
	27, // 21: varlet.v1.VarletService.RegisterCompletionHook:input_type -> varlet.v1.RegisterCompletionHookRequest
	29, // 22: varlet.v1.VarletService.DeregisterCompletionHook:input_type -> varlet.v1.DeregisterCompletionHookRequest
	31, // 23: varlet.v1.VarletService.ListCompletionHooks:input_type -> varlet.v1.ListCompletionHooksRequest
	2,  // 24: varlet.v1.VarletService.RegisterNamespace:output_type -> varlet.v1.RegisterNamespaceResponse
	4,  // 25: varlet.v1.VarletService.GetNamespace:output_type -> varlet.v1.GetNamespaceResponse
	16, // 26: varlet.v1.VarletService.SetNamespacePolicy:output_type -> varlet.v1.SetNamespacePolicyResponse
	6,  // 27: varlet.v1.VarletService.PutVariable:output_type -> varlet.v1.PutVariableResponse
	8,  // 28: varlet.v1.VarletService.DeleteVariable:output_type -> varlet.v1.DeleteVariableResponse
	10, // 29: varlet.v1.VarletService.RegisterConsumer:output_type -> varlet.v1.RegisterConsumerResponse
	12, // 30: varlet.v1.VarletService.DeregisterConsumer:output_type -> varlet.v1.DeregisterConsumerResponse
	14, // 31: varlet.v1.VarletService.GetVariableValue:output_type -> varlet.v1.GetVariableValueResponse
	26, // 32: varlet.v1.VarletService.StartActuation:output_type -> varlet.v1.StartActuationResponse
	19, // 33: varlet.v1.VarletService.GetDependencyGraph:output_type -> varlet.v1.GetDependencyGraphResponse
	24, // 34: varlet.v1.VarletService.GetActuationTrace:output_type -> varlet.v1.GetActuationTraceResponse
	28, // 35: varlet.v1.VarletService.RegisterCompletionHook:output_type -> varlet.v1.RegisterCompletionHookResponse
	30, // 36: varlet.v1.VarletService.DeregisterCompletionHook:output_type -> varlet.v1.DeregisterCompletionHookResponse
	32, // 37: varlet.v1.VarletService.ListCompletionHooks:output_type -> varlet.v1.ListCompletionHooksResponse
	24, // [24:38] is the sub-list for method output_type
	10, // [10:24] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_v1_varlet_proto_init() }
func file_proto_v1_varlet_proto_init() {
	if File_proto_v1_varlet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_varlet_proto_rawDesc), len(file_proto_v1_varlet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_varlet_proto_goTypes,
		DependencyIndexes: file_proto_v1_varlet_proto_depIdxs,
		MessageInfos:      file_proto_v1_varlet_proto_msgTypes,
	}.Build()
	File_proto_v1_varlet_proto = out.File
	file_proto_v1_varlet_proto_goTypes = nil
	file_proto_v1_varlet_proto_depIdxs = nil
}
