// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/v1/varlet.proto

package varletv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VarletService_RegisterNamespace_FullMethodName  = "/varlet.v1.VarletService/RegisterNamespace"
	VarletService_GetNamespace_FullMethodName       = "/varlet.v1.VarletService/GetNamespace"
	VarletService_SetNamespacePolicy_FullMethodName = "/varlet.v1.VarletService/SetNamespacePolicy"
	VarletService_PutVariable_FullMethodName        = "/varlet.v1.VarletService/PutVariable"
	VarletService_DeleteVariable_FullMethodName     = "/varlet.v1.VarletService/DeleteVariable"
	VarletService_RegisterConsumer_FullMethodName   = "/varlet.v1.VarletService/RegisterConsumer"
	VarletService_DeregisterConsumer_FullMethodName = "/varlet.v1.VarletService/DeregisterConsumer"
	VarletService_GetVariableValue_FullMethodName   = "/varlet.v1.VarletService/GetVariableValue"
	VarletService_GetDependencyGraph_FullMethodName = "/varlet.v1.VarletService/GetDependencyGraph"
)

// VarletServiceClient is the client API for VarletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service managing Varlet topologies, variables, and dependencies.
type VarletServiceClient interface {
	// Namespaces
	RegisterNamespace(ctx context.Context, in *RegisterNamespaceRequest, opts ...grpc.CallOption) (*RegisterNamespaceResponse, error)
	GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error)
	SetNamespacePolicy(ctx context.Context, in *SetNamespacePolicyRequest, opts ...grpc.CallOption) (*SetNamespacePolicyResponse, error)
	// Variables (Outputs)
	PutVariable(ctx context.Context, in *PutVariableRequest, opts ...grpc.CallOption) (*PutVariableResponse, error)
	DeleteVariable(ctx context.Context, in *DeleteVariableRequest, opts ...grpc.CallOption) (*DeleteVariableResponse, error)
	// Dependencies (Inputs)
	RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error)
	DeregisterConsumer(ctx context.Context, in *DeregisterConsumerRequest, opts ...grpc.CallOption) (*DeregisterConsumerResponse, error)
	GetVariableValue(ctx context.Context, in *GetVariableValueRequest, opts ...grpc.CallOption) (*GetVariableValueResponse, error)
	// Graph operations
	GetDependencyGraph(ctx context.Context, in *GetDependencyGraphRequest, opts ...grpc.CallOption) (*GetDependencyGraphResponse, error)
}

type varletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVarletServiceClient(cc grpc.ClientConnInterface) VarletServiceClient {
	return &varletServiceClient{cc}
}

func (c *varletServiceClient) RegisterNamespace(ctx context.Context, in *RegisterNamespaceRequest, opts ...grpc.CallOption) (*RegisterNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNamespaceResponse)
	err := c.cc.Invoke(ctx, VarletService_RegisterNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceResponse)
	err := c.cc.Invoke(ctx, VarletService_GetNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) SetNamespacePolicy(ctx context.Context, in *SetNamespacePolicyRequest, opts ...grpc.CallOption) (*SetNamespacePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNamespacePolicyResponse)
	err := c.cc.Invoke(ctx, VarletService_SetNamespacePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) PutVariable(ctx context.Context, in *PutVariableRequest, opts ...grpc.CallOption) (*PutVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutVariableResponse)
	err := c.cc.Invoke(ctx, VarletService_PutVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) DeleteVariable(ctx context.Context, in *DeleteVariableRequest, opts ...grpc.CallOption) (*DeleteVariableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVariableResponse)
	err := c.cc.Invoke(ctx, VarletService_DeleteVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) RegisterConsumer(ctx context.Context, in *RegisterConsumerRequest, opts ...grpc.CallOption) (*RegisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterConsumerResponse)
	err := c.cc.Invoke(ctx, VarletService_RegisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) DeregisterConsumer(ctx context.Context, in *DeregisterConsumerRequest, opts ...grpc.CallOption) (*DeregisterConsumerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterConsumerResponse)
	err := c.cc.Invoke(ctx, VarletService_DeregisterConsumer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) GetVariableValue(ctx context.Context, in *GetVariableValueRequest, opts ...grpc.CallOption) (*GetVariableValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVariableValueResponse)
	err := c.cc.Invoke(ctx, VarletService_GetVariableValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *varletServiceClient) GetDependencyGraph(ctx context.Context, in *GetDependencyGraphRequest, opts ...grpc.CallOption) (*GetDependencyGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDependencyGraphResponse)
	err := c.cc.Invoke(ctx, VarletService_GetDependencyGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VarletServiceServer is the server API for VarletService service.
// All implementations must embed UnimplementedVarletServiceServer
// for forward compatibility.
//
// Service managing Varlet topologies, variables, and dependencies.
type VarletServiceServer interface {
	// Namespaces
	RegisterNamespace(context.Context, *RegisterNamespaceRequest) (*RegisterNamespaceResponse, error)
	GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error)
	SetNamespacePolicy(context.Context, *SetNamespacePolicyRequest) (*SetNamespacePolicyResponse, error)
	// Variables (Outputs)
	PutVariable(context.Context, *PutVariableRequest) (*PutVariableResponse, error)
	DeleteVariable(context.Context, *DeleteVariableRequest) (*DeleteVariableResponse, error)
	// Dependencies (Inputs)
	RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error)
	DeregisterConsumer(context.Context, *DeregisterConsumerRequest) (*DeregisterConsumerResponse, error)
	GetVariableValue(context.Context, *GetVariableValueRequest) (*GetVariableValueResponse, error)
	// Graph operations
	GetDependencyGraph(context.Context, *GetDependencyGraphRequest) (*GetDependencyGraphResponse, error)
	mustEmbedUnimplementedVarletServiceServer()
}

// UnimplementedVarletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVarletServiceServer struct{}

func (UnimplementedVarletServiceServer) RegisterNamespace(context.Context, *RegisterNamespaceRequest) (*RegisterNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNamespace not implemented")
}
func (UnimplementedVarletServiceServer) GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespace not implemented")
}
func (UnimplementedVarletServiceServer) SetNamespacePolicy(context.Context, *SetNamespacePolicyRequest) (*SetNamespacePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNamespacePolicy not implemented")
}
func (UnimplementedVarletServiceServer) PutVariable(context.Context, *PutVariableRequest) (*PutVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutVariable not implemented")
}
func (UnimplementedVarletServiceServer) DeleteVariable(context.Context, *DeleteVariableRequest) (*DeleteVariableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVariable not implemented")
}
func (UnimplementedVarletServiceServer) RegisterConsumer(context.Context, *RegisterConsumerRequest) (*RegisterConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterConsumer not implemented")
}
func (UnimplementedVarletServiceServer) DeregisterConsumer(context.Context, *DeregisterConsumerRequest) (*DeregisterConsumerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterConsumer not implemented")
}
func (UnimplementedVarletServiceServer) GetVariableValue(context.Context, *GetVariableValueRequest) (*GetVariableValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVariableValue not implemented")
}
func (UnimplementedVarletServiceServer) GetDependencyGraph(context.Context, *GetDependencyGraphRequest) (*GetDependencyGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDependencyGraph not implemented")
}
func (UnimplementedVarletServiceServer) mustEmbedUnimplementedVarletServiceServer() {}
func (UnimplementedVarletServiceServer) testEmbeddedByValue()                       {}

// UnsafeVarletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VarletServiceServer will
// result in compilation errors.
type UnsafeVarletServiceServer interface {
	mustEmbedUnimplementedVarletServiceServer()
}

func RegisterVarletServiceServer(s grpc.ServiceRegistrar, srv VarletServiceServer) {
	// If the following call panics, it indicates UnimplementedVarletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VarletService_ServiceDesc, srv)
}

func _VarletService_RegisterNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).RegisterNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_RegisterNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).RegisterNamespace(ctx, req.(*RegisterNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_GetNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).GetNamespace(ctx, req.(*GetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_SetNamespacePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNamespacePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).SetNamespacePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_SetNamespacePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).SetNamespacePolicy(ctx, req.(*SetNamespacePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_PutVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).PutVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_PutVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).PutVariable(ctx, req.(*PutVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_DeleteVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).DeleteVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_DeleteVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).DeleteVariable(ctx, req.(*DeleteVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_RegisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).RegisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_RegisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).RegisterConsumer(ctx, req.(*RegisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_DeregisterConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).DeregisterConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_DeregisterConsumer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).DeregisterConsumer(ctx, req.(*DeregisterConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_GetVariableValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariableValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).GetVariableValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_GetVariableValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).GetVariableValue(ctx, req.(*GetVariableValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VarletService_GetDependencyGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDependencyGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarletServiceServer).GetDependencyGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarletService_GetDependencyGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarletServiceServer).GetDependencyGraph(ctx, req.(*GetDependencyGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VarletService_ServiceDesc is the grpc.ServiceDesc for VarletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VarletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "varlet.v1.VarletService",
	HandlerType: (*VarletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNamespace",
			Handler:    _VarletService_RegisterNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _VarletService_GetNamespace_Handler,
		},
		{
			MethodName: "SetNamespacePolicy",
			Handler:    _VarletService_SetNamespacePolicy_Handler,
		},
		{
			MethodName: "PutVariable",
			Handler:    _VarletService_PutVariable_Handler,
		},
		{
			MethodName: "DeleteVariable",
			Handler:    _VarletService_DeleteVariable_Handler,
		},
		{
			MethodName: "RegisterConsumer",
			Handler:    _VarletService_RegisterConsumer_Handler,
		},
		{
			MethodName: "DeregisterConsumer",
			Handler:    _VarletService_DeregisterConsumer_Handler,
		},
		{
			MethodName: "GetVariableValue",
			Handler:    _VarletService_GetVariableValue_Handler,
		},
		{
			MethodName: "GetDependencyGraph",
			Handler:    _VarletService_GetDependencyGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/varlet.proto",
}
