// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/v1/varlet.proto

package varletv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetentionPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinVersions   int32                  `protobuf:"varint,1,opt,name=min_versions,json=minVersions,proto3" json:"min_versions,omitempty"`
	MaxAgeDays    int32                  `protobuf:"varint,2,opt,name=max_age_days,json=maxAgeDays,proto3" json:"max_age_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	mi := &file_proto_v1_varlet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{0}
}

func (x *RetentionPolicy) GetMinVersions() int32 {
	if x != nil {
		return x.MinVersions
	}
	return 0
}

func (x *RetentionPolicy) GetMaxAgeDays() int32 {
	if x != nil {
		return x.MaxAgeDays
	}
	return 0
}

type RegisterNamespaceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RetentionPolicy *RetentionPolicy       `protobuf:"bytes,2,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	RunWebhookUrl   string                 `protobuf:"bytes,3,opt,name=run_webhook_url,json=runWebhookUrl,proto3" json:"run_webhook_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterNamespaceRequest) Reset() {
	*x = RegisterNamespaceRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNamespaceRequest) ProtoMessage() {}

func (x *RegisterNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNamespaceRequest.ProtoReflect.Descriptor instead.
func (*RegisterNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterNamespaceRequest) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *RegisterNamespaceRequest) GetRunWebhookUrl() string {
	if x != nil {
		return x.RunWebhookUrl
	}
	return ""
}

type RegisterNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNamespaceResponse) Reset() {
	*x = RegisterNamespaceResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNamespaceResponse) ProtoMessage() {}

func (x *RegisterNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNamespaceResponse.ProtoReflect.Descriptor instead.
func (*RegisterNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNamespaceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{3}
}

func (x *GetNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNamespaceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllowedConsumers []string               `protobuf:"bytes,2,rep,name=allowed_consumers,json=allowedConsumers,proto3" json:"allowed_consumers,omitempty"` // Allowlist of consumer namespaces (supports wildcards)
	RetentionPolicy  *RetentionPolicy       `protobuf:"bytes,3,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	RunWebhookUrl    string                 `protobuf:"bytes,4,opt,name=run_webhook_url,json=runWebhookUrl,proto3" json:"run_webhook_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNamespaceResponse) Reset() {
	*x = GetNamespaceResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceResponse) ProtoMessage() {}

func (x *GetNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{4}
}

func (x *GetNamespaceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNamespaceResponse) GetAllowedConsumers() []string {
	if x != nil {
		return x.AllowedConsumers
	}
	return nil
}

func (x *GetNamespaceResponse) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *GetNamespaceResponse) GetRunWebhookUrl() string {
	if x != nil {
		return x.RunWebhookUrl
	}
	return ""
}

type PutVariableRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value          *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ForceActuation bool                   `protobuf:"varint,4,opt,name=force_actuation,json=forceActuation,proto3" json:"force_actuation,omitempty"` // If true, force consumers to re-apply even if value is unchanged
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutVariableRequest) Reset() {
	*x = PutVariableRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVariableRequest) ProtoMessage() {}

func (x *PutVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVariableRequest.ProtoReflect.Descriptor instead.
func (*PutVariableRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{5}
}

func (x *PutVariableRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutVariableRequest) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutVariableRequest) GetForceActuation() bool {
	if x != nil {
		return x.ForceActuation
	}
	return false
}

type PutVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutVariableResponse) Reset() {
	*x = PutVariableResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutVariableResponse) ProtoMessage() {}

func (x *PutVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutVariableResponse.ProtoReflect.Descriptor instead.
func (*PutVariableResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{6}
}

type DeleteVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"` // If true, force deletion even if there are active consumers.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableRequest) Reset() {
	*x = DeleteVariableRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableRequest) ProtoMessage() {}

func (x *DeleteVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableRequest.ProtoReflect.Descriptor instead.
func (*DeleteVariableRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVariableRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteVariableRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableResponse) Reset() {
	*x = DeleteVariableResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableResponse) ProtoMessage() {}

func (x *DeleteVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableResponse.ProtoReflect.Descriptor instead.
func (*DeleteVariableResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{8}
}

type RegisterConsumerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterConsumerRequest) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *RegisterConsumerRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *RegisterConsumerRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type RegisterConsumerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`                                          // Returns the current value upon registration
	ActuationNonce int64                  `protobuf:"varint,2,opt,name=actuation_nonce,json=actuationNonce,proto3" json:"actuation_nonce,omitempty"` // Token to trigger downstream recreation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterConsumerResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RegisterConsumerResponse) GetActuationNonce() int64 {
	if x != nil {
		return x.ActuationNonce
	}
	return 0
}

type DeregisterConsumerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeregisterConsumerRequest) Reset() {
	*x = DeregisterConsumerRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterConsumerRequest) ProtoMessage() {}

func (x *DeregisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{11}
}

func (x *DeregisterConsumerRequest) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *DeregisterConsumerRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *DeregisterConsumerRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type DeregisterConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterConsumerResponse) Reset() {
	*x = DeregisterConsumerResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterConsumerResponse) ProtoMessage() {}

func (x *DeregisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{12}
}

type GetVariableValueRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetVariableValueRequest) Reset() {
	*x = GetVariableValueRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableValueRequest) ProtoMessage() {}

func (x *GetVariableValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableValueRequest.ProtoReflect.Descriptor instead.
func (*GetVariableValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{13}
}

func (x *GetVariableValueRequest) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *GetVariableValueRequest) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *GetVariableValueRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type GetVariableValueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          *structpb.Value        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ActuationNonce int64                  `protobuf:"varint,2,opt,name=actuation_nonce,json=actuationNonce,proto3" json:"actuation_nonce,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVariableValueResponse) Reset() {
	*x = GetVariableValueResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableValueResponse) ProtoMessage() {}

func (x *GetVariableValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableValueResponse.ProtoReflect.Descriptor instead.
func (*GetVariableValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{14}
}

func (x *GetVariableValueResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetVariableValueResponse) GetActuationNonce() int64 {
	if x != nil {
		return x.ActuationNonce
	}
	return 0
}

type SetNamespacePolicyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AllowedConsumers []string               `protobuf:"bytes,2,rep,name=allowed_consumers,json=allowedConsumers,proto3" json:"allowed_consumers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetNamespacePolicyRequest) Reset() {
	*x = SetNamespacePolicyRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespacePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespacePolicyRequest) ProtoMessage() {}

func (x *SetNamespacePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespacePolicyRequest.ProtoReflect.Descriptor instead.
func (*SetNamespacePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{15}
}

func (x *SetNamespacePolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetNamespacePolicyRequest) GetAllowedConsumers() []string {
	if x != nil {
		return x.AllowedConsumers
	}
	return nil
}

type SetNamespacePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNamespacePolicyResponse) Reset() {
	*x = SetNamespacePolicyResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNamespacePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNamespacePolicyResponse) ProtoMessage() {}

func (x *SetNamespacePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNamespacePolicyResponse.ProtoReflect.Descriptor instead.
func (*SetNamespacePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{16}
}

type GetDependencyGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"` // Optional root namespace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependencyGraphRequest) Reset() {
	*x = GetDependencyGraphRequest{}
	mi := &file_proto_v1_varlet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependencyGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyGraphRequest) ProtoMessage() {}

func (x *GetDependencyGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyGraphRequest.ProtoReflect.Descriptor instead.
func (*GetDependencyGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{17}
}

func (x *GetDependencyGraphRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DependencyEdge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsumerNamespace string                 `protobuf:"bytes,1,opt,name=consumer_namespace,json=consumerNamespace,proto3" json:"consumer_namespace,omitempty"`
	SourceNamespace   string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	VariableName      string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DependencyEdge) Reset() {
	*x = DependencyEdge{}
	mi := &file_proto_v1_varlet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyEdge) ProtoMessage() {}

func (x *DependencyEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyEdge.ProtoReflect.Descriptor instead.
func (*DependencyEdge) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{18}
}

func (x *DependencyEdge) GetConsumerNamespace() string {
	if x != nil {
		return x.ConsumerNamespace
	}
	return ""
}

func (x *DependencyEdge) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *DependencyEdge) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

type GetDependencyGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Edges         []*DependencyEdge      `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependencyGraphResponse) Reset() {
	*x = GetDependencyGraphResponse{}
	mi := &file_proto_v1_varlet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependencyGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyGraphResponse) ProtoMessage() {}

func (x *GetDependencyGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_varlet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyGraphResponse.ProtoReflect.Descriptor instead.
func (*GetDependencyGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_varlet_proto_rawDescGZIP(), []int{19}
}

func (x *GetDependencyGraphResponse) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *GetDependencyGraphResponse) GetEdges() []*DependencyEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_proto_v1_varlet_proto protoreflect.FileDescriptor

const file_proto_v1_varlet_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/varlet.proto\x12\tvarlet.v1\x1a\x1cgoogle/protobuf/struct.proto\"V\n" +
	"\x0fRetentionPolicy\x12!\n" +
	"\fmin_versions\x18\x01 \x01(\x05R\vminVersions\x12 \n" +
	"\fmax_age_days\x18\x02 \x01(\x05R\n" +
	"maxAgeDays\"\x9d\x01\n" +
	"\x18RegisterNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12E\n" +
	"\x10retention_policy\x18\x02 \x01(\v2\x1a.varlet.v1.RetentionPolicyR\x0fretentionPolicy\x12&\n" +
	"\x0frun_webhook_url\x18\x03 \x01(\tR\rrunWebhookUrl\"/\n" +
	"\x19RegisterNamespaceResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13GetNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc6\x01\n" +
	"\x14GetNamespaceResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x11allowed_consumers\x18\x02 \x03(\tR\x10allowedConsumers\x12E\n" +
	"\x10retention_policy\x18\x03 \x01(\v2\x1a.varlet.v1.RetentionPolicyR\x0fretentionPolicy\x12&\n" +
	"\x0frun_webhook_url\x18\x04 \x01(\tR\rrunWebhookUrl\"\x9d\x01\n" +
	"\x12PutVariableRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12'\n" +
	"\x0fforce_actuation\x18\x04 \x01(\bR\x0eforceActuation\"\x15\n" +
	"\x13PutVariableResponse\"_\n" +
	"\x15DeleteVariableRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x18\n" +
	"\x16DeleteVariableResponse\"\x98\x01\n" +
	"\x17RegisterConsumerRequest\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"q\n" +
	"\x18RegisterConsumerResponse\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12'\n" +
	"\x0factuation_nonce\x18\x02 \x01(\x03R\x0eactuationNonce\"\x9a\x01\n" +
	"\x19DeregisterConsumerRequest\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"\x1c\n" +
	"\x1aDeregisterConsumerResponse\"\x98\x01\n" +
	"\x17GetVariableValueRequest\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"q\n" +
	"\x18GetVariableValueResponse\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12'\n" +
	"\x0factuation_nonce\x18\x02 \x01(\x03R\x0eactuationNonce\"f\n" +
	"\x19SetNamespacePolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12+\n" +
	"\x11allowed_consumers\x18\x02 \x03(\tR\x10allowedConsumers\"\x1c\n" +
	"\x1aSetNamespacePolicyResponse\"9\n" +
	"\x19GetDependencyGraphRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x8f\x01\n" +
	"\x0eDependencyEdge\x12-\n" +
	"\x12consumer_namespace\x18\x01 \x01(\tR\x11consumerNamespace\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\"m\n" +
	"\x1aGetDependencyGraphResponse\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12/\n" +
	"\x05edges\x18\x02 \x03(\v2\x19.varlet.v1.DependencyEdgeR\x05edges2\xc8\x06\n" +
	"\rVarletService\x12^\n" +
	"\x11RegisterNamespace\x12#.varlet.v1.RegisterNamespaceRequest\x1a$.varlet.v1.RegisterNamespaceResponse\x12O\n" +
	"\fGetNamespace\x12\x1e.varlet.v1.GetNamespaceRequest\x1a\x1f.varlet.v1.GetNamespaceResponse\x12a\n" +
	"\x12SetNamespacePolicy\x12$.varlet.v1.SetNamespacePolicyRequest\x1a%.varlet.v1.SetNamespacePolicyResponse\x12L\n" +
	"\vPutVariable\x12\x1d.varlet.v1.PutVariableRequest\x1a\x1e.varlet.v1.PutVariableResponse\x12U\n" +
	"\x0eDeleteVariable\x12 .varlet.v1.DeleteVariableRequest\x1a!.varlet.v1.DeleteVariableResponse\x12[\n" +
	"\x10RegisterConsumer\x12\".varlet.v1.RegisterConsumerRequest\x1a#.varlet.v1.RegisterConsumerResponse\x12a\n" +
	"\x12DeregisterConsumer\x12$.varlet.v1.DeregisterConsumerRequest\x1a%.varlet.v1.DeregisterConsumerResponse\x12[\n" +
	"\x10GetVariableValue\x12\".varlet.v1.GetVariableValueRequest\x1a#.varlet.v1.GetVariableValueResponse\x12a\n" +
	"\x12GetDependencyGraph\x12$.varlet.v1.GetDependencyGraphRequest\x1a%.varlet.v1.GetDependencyGraphResponseB,Z*github.com/google/varlet/proto/v1;varletv1b\x06proto3"

var (
	file_proto_v1_varlet_proto_rawDescOnce sync.Once
	file_proto_v1_varlet_proto_rawDescData []byte
)

func file_proto_v1_varlet_proto_rawDescGZIP() []byte {
	file_proto_v1_varlet_proto_rawDescOnce.Do(func() {
		file_proto_v1_varlet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_varlet_proto_rawDesc), len(file_proto_v1_varlet_proto_rawDesc)))
	})
	return file_proto_v1_varlet_proto_rawDescData
}

var file_proto_v1_varlet_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_v1_varlet_proto_goTypes = []any{
	(*RetentionPolicy)(nil),            // 0: varlet.v1.RetentionPolicy
	(*RegisterNamespaceRequest)(nil),   // 1: varlet.v1.RegisterNamespaceRequest
	(*RegisterNamespaceResponse)(nil),  // 2: varlet.v1.RegisterNamespaceResponse
	(*GetNamespaceRequest)(nil),        // 3: varlet.v1.GetNamespaceRequest
	(*GetNamespaceResponse)(nil),       // 4: varlet.v1.GetNamespaceResponse
	(*PutVariableRequest)(nil),         // 5: varlet.v1.PutVariableRequest
	(*PutVariableResponse)(nil),        // 6: varlet.v1.PutVariableResponse
	(*DeleteVariableRequest)(nil),      // 7: varlet.v1.DeleteVariableRequest
	(*DeleteVariableResponse)(nil),     // 8: varlet.v1.DeleteVariableResponse
	(*RegisterConsumerRequest)(nil),    // 9: varlet.v1.RegisterConsumerRequest
	(*RegisterConsumerResponse)(nil),   // 10: varlet.v1.RegisterConsumerResponse
	(*DeregisterConsumerRequest)(nil),  // 11: varlet.v1.DeregisterConsumerRequest
	(*DeregisterConsumerResponse)(nil), // 12: varlet.v1.DeregisterConsumerResponse
	(*GetVariableValueRequest)(nil),    // 13: varlet.v1.GetVariableValueRequest
	(*GetVariableValueResponse)(nil),   // 14: varlet.v1.GetVariableValueResponse
	(*SetNamespacePolicyRequest)(nil),  // 15: varlet.v1.SetNamespacePolicyRequest
	(*SetNamespacePolicyResponse)(nil), // 16: varlet.v1.SetNamespacePolicyResponse
	(*GetDependencyGraphRequest)(nil),  // 17: varlet.v1.GetDependencyGraphRequest
	(*DependencyEdge)(nil),             // 18: varlet.v1.DependencyEdge
	(*GetDependencyGraphResponse)(nil), // 19: varlet.v1.GetDependencyGraphResponse
	(*structpb.Value)(nil),             // 20: google.protobuf.Value
}
var file_proto_v1_varlet_proto_depIdxs = []int32{
	0,  // 0: varlet.v1.RegisterNamespaceRequest.retention_policy:type_name -> varlet.v1.RetentionPolicy
	0,  // 1: varlet.v1.GetNamespaceResponse.retention_policy:type_name -> varlet.v1.RetentionPolicy
	20, // 2: varlet.v1.PutVariableRequest.value:type_name -> google.protobuf.Value
	20, // 3: varlet.v1.RegisterConsumerResponse.value:type_name -> google.protobuf.Value
	20, // 4: varlet.v1.GetVariableValueResponse.value:type_name -> google.protobuf.Value
	18, // 5: varlet.v1.GetDependencyGraphResponse.edges:type_name -> varlet.v1.DependencyEdge
	1,  // 6: varlet.v1.VarletService.RegisterNamespace:input_type -> varlet.v1.RegisterNamespaceRequest
	3,  // 7: varlet.v1.VarletService.GetNamespace:input_type -> varlet.v1.GetNamespaceRequest
	15, // 8: varlet.v1.VarletService.SetNamespacePolicy:input_type -> varlet.v1.SetNamespacePolicyRequest
	5,  // 9: varlet.v1.VarletService.PutVariable:input_type -> varlet.v1.PutVariableRequest
	7,  // 10: varlet.v1.VarletService.DeleteVariable:input_type -> varlet.v1.DeleteVariableRequest
	9,  // 11: varlet.v1.VarletService.RegisterConsumer:input_type -> varlet.v1.RegisterConsumerRequest
	11, // 12: varlet.v1.VarletService.DeregisterConsumer:input_type -> varlet.v1.DeregisterConsumerRequest
	13, // 13: varlet.v1.VarletService.GetVariableValue:input_type -> varlet.v1.GetVariableValueRequest
	17, // 14: varlet.v1.VarletService.GetDependencyGraph:input_type -> varlet.v1.GetDependencyGraphRequest
	2,  // 15: varlet.v1.VarletService.RegisterNamespace:output_type -> varlet.v1.RegisterNamespaceResponse
	4,  // 16: varlet.v1.VarletService.GetNamespace:output_type -> varlet.v1.GetNamespaceResponse
	16, // 17: varlet.v1.VarletService.SetNamespacePolicy:output_type -> varlet.v1.SetNamespacePolicyResponse
	6,  // 18: varlet.v1.VarletService.PutVariable:output_type -> varlet.v1.PutVariableResponse
	8,  // 19: varlet.v1.VarletService.DeleteVariable:output_type -> varlet.v1.DeleteVariableResponse
	10, // 20: varlet.v1.VarletService.RegisterConsumer:output_type -> varlet.v1.RegisterConsumerResponse
	12, // 21: varlet.v1.VarletService.DeregisterConsumer:output_type -> varlet.v1.DeregisterConsumerResponse
	14, // 22: varlet.v1.VarletService.GetVariableValue:output_type -> varlet.v1.GetVariableValueResponse
	19, // 23: varlet.v1.VarletService.GetDependencyGraph:output_type -> varlet.v1.GetDependencyGraphResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_v1_varlet_proto_init() }
func file_proto_v1_varlet_proto_init() {
	if File_proto_v1_varlet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_varlet_proto_rawDesc), len(file_proto_v1_varlet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_varlet_proto_goTypes,
		DependencyIndexes: file_proto_v1_varlet_proto_depIdxs,
		MessageInfos:      file_proto_v1_varlet_proto_msgTypes,
	}.Build()
	File_proto_v1_varlet_proto = out.File
	file_proto_v1_varlet_proto_goTypes = nil
	file_proto_v1_varlet_proto_depIdxs = nil
}
